server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ocbc-finance-contract-test
  
  # 测试数据库配置（使用H2内存数据库）
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
  
  # Flyway配置（测试环境禁用）
  flyway:
    enabled: false
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# 日志配置
logging:
  level:
    com.ocbc.finance: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用自定义配置
app:
  # Gemini AI配置（测试环境禁用）
  gemini:
    api-key: test-api-key
    model: gemini-2.0-flash
    timeout: 5000
    enabled: false
  
  # 文件处理配置
  file:
    upload-dir: /tmp/test-uploads
    max-size: 10MB
    allowed-types: application/pdf
  
  # 业务配置
  business:
    default-currency: SGD
    booking-day: 27
    created-by: test-system
